import express from 'express';import {DatabaseSync as Database} from 'node:sqlite';import path from 'path';import {fileURLToPath} from 'url';import fs from 'fs';
const __d=path.dirname(fileURLToPath(import.meta.url));const db=new Database(process.env.DB||path.join(__d,'mac.db'));
const KEY=process.env.ADMIN_KEY||'cambiame-ya';
db.exec(`create table if not exists submissions(id integer primary key autoincrement,kind text not null,data text not null,created text default current_timestamp);
create table if not exists members(id integer primary key autoincrement,codigo text,tipo text,tipo_doc text,documento text,nombre text,apellidos text,nacimiento text,email text,celular text,departamento text,municipio text,juvenil integer default 0,tutor text,estado text,created text default current_timestamp,retiro text);
create table if not exists movimientos(id integer primary key autoincrement,campana text,tipo text,concepto text,fecha text,monto real);
create table if not exists news(id integer primary key autoincrement,title text not null,body text not null,created text default current_timestamp);`);
if(!db.prepare('select count(*) c from news').get().c)db.prepare('insert into news(title,body) values(?,?)').run('Nace el Movimiento Alternativa Ciudadana','El 30 de agosto de 2026 se constituyó en Cali el MAC, por iniciativa de Iris Maia Escorcia.');
const app=express();app.use(express.json({limit:'50kb'}));
const hits=new Map();app.use('/api',(q,r,n)=>{const k=q.ip,t=Date.now(),a=(hits.get(k)||[]).filter(x=>t-x<60000);a.push(t);hits.set(k,a);a.length>40?r.status(429).json({error:'Demasiadas solicitudes. Intenta en un minuto.'}):n()});
const S={voluntariado:['nombre','email','municipio','area'],contacto:['nombre','email','mensaje'],donacion:['nombre','email','monto']};
const mail=/^[^@\s]+@[^@\s]+\.[^@\s]+$/;
const auth=(q,r,n)=>q.get('x-admin-key')===KEY?n():r.status(401).json({error:'Clave incorrecta'});
app.get('/api/news',(q,r)=>r.json(db.prepare('select * from news order by id desc').all()));
app.get('/api/admin/submissions',auth,(q,r)=>r.json(db.prepare('select * from submissions order by id desc limit 500').all().map(x=>({...x,data:JSON.parse(x.data)}))));
app.post('/api/admin/news',auth,(q,r)=>{const{title,body}=q.body;if(!title||!body)return r.status(400).json({error:'Título y texto son obligatorios'});r.json({id:db.prepare('insert into news(title,body) values(?,?)').run(title,body).lastInsertRowid})});
app.delete('/api/admin/news/:id',auth,(q,r)=>{db.prepare('delete from news where id=?').run(q.params.id);r.json({ok:true})});
const age=b=>Math.floor((Date.now()-new Date(b))/31557600000);const bad=(r,m)=>r.status(400).json({error:m});
app.post('/api/afiliacion',(q,r)=>{const d=q.body||{};if(d.web)return r.json({ok:true});
 for(const x of ['tipo','tipo_doc','documento','nombre','apellidos','nacimiento','email','celular','departamento','municipio','tratamiento_datos'])if(!d[x])return bad(r,`Falta el campo: ${x}`);
 if(!['simpatizante','militante'].includes(d.tipo))return bad(r,'Tipo no válido');if(!mail.test(d.email))return bad(r,'Correo no válido');
 if(isNaN(new Date(d.nacimiento)))return bad(r,'Fecha no válida');const a=age(d.nacimiento);if(a<14)return bad(r,'La afiliación es desde los 14 años (art. 14).');
 if(d.tipo==='militante'&&!(d.nacionalidad&&d.acepta_estatutos&&d.sin_doble_militancia))return bad(r,'Para ser militante debes aceptar todas las declaraciones.');
 if(a<18){if(!(d.tutor_nombre&&d.tutor_documento&&d.tutor_autoriza))return bad(r,'Menores de 18: se requiere nombre, documento y autorización del representante legal (art. 18B).');if(d.tipo==='militante'&&d.tipo_doc!=='Tarjeta de identidad')return bad(r,'Los militantes menores de edad deben presentar tarjeta de identidad (art. 18A).');}
 if(db.prepare("select id from members where documento=? and estado!='retirado'").get(String(d.documento)))return r.status(409).json({error:'Ya existe una afiliación con ese documento. Consulta tu certificado en Mi afiliación.'});
 const estado=d.tipo==='militante'?'pendiente':'activo';
 const id=Number(db.prepare('insert into members(tipo,tipo_doc,documento,nombre,apellidos,nacimiento,email,celular,departamento,municipio,juvenil,tutor,estado) values(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(d.tipo,d.tipo_doc,String(d.documento),d.nombre,d.apellidos,d.nacimiento,d.email.toLowerCase(),d.celular,d.departamento,d.municipio,a<18?1:0,a<18?JSON.stringify({n:d.tutor_nombre,d:d.tutor_documento}):'',estado).lastInsertRowid);
 const codigo='MAC-'+String(id).padStart(6,'0');db.prepare('update members set codigo=? where id=?').run(codigo,id);r.json({ok:true,codigo,estado,tipo:d.tipo});});
const mine=(d)=>d&&d.documento&&d.email?db.prepare('select * from members where documento=? and email=? order by id desc').get(String(d.documento),String(d.email).toLowerCase()):null;
app.post('/api/certificado',(q,r)=>{const m=mine(q.body);if(!m)return r.status(404).json({error:'No encontramos una afiliación con esos datos.'});r.json({codigo:m.codigo,nombre:m.nombre+' '+m.apellidos,tipo:m.tipo,estado:m.estado,created:m.created,juvenil:!!m.juvenil});});
app.post('/api/renuncia',(q,r)=>{const m=mine(q.body);if(!m||m.estado==='retirado')return r.status(404).json({error:'No encontramos una afiliación activa con esos datos.'});
 db.prepare("update members set estado='retirado',retiro=current_timestamp,celular=case when juvenil=1 then '' else celular end,tutor=case when juvenil=1 then '' else tutor end where id=?").run(m.id);
 db.prepare('insert into submissions(kind,data) values(?,?)').run('renuncia',JSON.stringify({codigo:m.codigo,motivo:q.body.motivo||''}));r.json({ok:true});});
app.post('/api/aval',(q,r)=>{const d=q.body||{};const m=mine(d);if(!m||m.tipo!=='militante'||m.estado!=='activo')return bad(r,'Solo pueden pedir aval los militantes activos. Si te afiliaste hace poco, tu solicitud puede estar pendiente de validación.');
 if(!d.cargo||!d.territorio||!d.mensaje)return bad(r,'Completa todos los campos');if(age(m.nacimiento)<18&&d.cargo!=='Consejo de Juventud')return bad(r,'Los menores de 18 solo pueden aspirar a Consejos de Juventud (art. 18E).');
 db.prepare('insert into submissions(kind,data) values(?,?)').run('aval',JSON.stringify({codigo:m.codigo,cargo:d.cargo,territorio:d.territorio,mensaje:d.mensaje}));r.json({ok:true});});
app.get('/api/finanzas',(q,r)=>{const rows=db.prepare('select * from movimientos order by fecha desc,id desc').all();const by={};for(const m of rows){const c=by[m.campana]||(by[m.campana]={nombre:m.campana,ingresos:0,gastos:0,saldo:0,movimientos:[]});m.tipo==='ingreso'?c.ingresos+=m.monto:c.gastos+=m.monto;c.saldo=c.ingresos-c.gastos;c.movimientos.push(m)}r.json({campanas:Object.values(by)})});
app.get('/api/admin/members',auth,(q,r)=>r.json(db.prepare('select * from members order by id desc limit 1000').all()));
app.post('/api/admin/members/:id',auth,(q,r)=>{if(!['activo','suspendido','retirado','pendiente'].includes(q.body.estado))return bad(r,'Estado no válido');db.prepare('update members set estado=? where id=?').run(q.body.estado,q.params.id);r.json({ok:true})});
app.post('/api/admin/movimientos',auth,(q,r)=>{const m=q.body;if(!m.campana||!m.concepto||!m.fecha||!(Number(m.monto)>0)||!['ingreso','gasto'].includes(m.tipo))return bad(r,'Datos del movimiento incompletos');db.prepare('insert into movimientos(campana,tipo,concepto,fecha,monto) values(?,?,?,?,?)').run(m.campana,m.tipo,m.concepto,m.fecha,Number(m.monto));r.json({ok:true})});
app.post('/api/:kind',(q,r)=>{const k=q.params.kind,f=S[k];if(!f)return r.status(404).json({error:'No existe'});const d=q.body||{};
 if(d.web)return r.json({ok:true});
 for(const x of f)if(!d[x])return r.status(400).json({error:`Falta el campo: ${x}`});
 if(!mail.test(d.email))return r.status(400).json({error:'Correo no válido'});
 if(k==='afiliacion'){const b=new Date(d.nacimiento);if(isNaN(b))return r.status(400).json({error:'Fecha no válida'});
  const age=Math.floor((Date.now()-b)/31557600000);if(age<14)return r.status(400).json({error:'La afiliación es desde los 14 años (art. 14).'});
  if(age<18&&!(d.tutor_nombre&&d.tutor_autoriza))return r.status(400).json({error:'Menores de 18: se requiere nombre y autorización del representante legal (art. 18B).'});d.menor=age<18;}
 if(k==='donacion'&&!(Number(d.monto)>0))return r.status(400).json({error:'Monto no válido'});
 const id=db.prepare('insert into submissions(kind,data) values(?,?)').run(k,JSON.stringify(d)).lastInsertRowid;r.json({ok:true,id});});
const dist=path.join(__d,'../dist');if(fs.existsSync(dist)){app.use(express.static(dist));app.get('*',(q,r)=>r.sendFile(path.join(dist,'index.html')))}
app.listen(process.env.PORT||3001,()=>console.log('MAC listo'));
