import {useState,useEffect} from 'react';import {Routes,Route,NavLink,Link} from 'react-router-dom';import {valores,ejes,ideas,tecno,regiones} from './content.js';import {plan} from './plan.js';import {NETLIFY,submit,getJSON,validar} from './api.js';
const Logo=({s=40})=><img src="/simbolo.svg" width={s} height={s} alt=""/>;
const nav=[['/nosotros','Nosotros'],['/programa','Programa'],['/plan','Plan de gobierno'],['/juventud','Juventud'],['/noticias','Noticias'],['/transparencia','Transparencia'],['/contacto','Contacto']];
const W=({children,cls=''})=><div className={`mx-auto max-w-5xl px-5 ${cls}`}>{children}</div>;
const H=({t,sub})=><header className="bg-morado text-white py-14"><W><h1 className="text-4xl md:text-6xl font-extrabold tracking-tight">{t}</h1>{sub&&<p className="mt-3 max-w-2xl text-white/85">{sub}</p>}</W></header>;
const Btn=({to,children,alt})=><Link to={to} className={`inline-block rounded-full px-6 py-3 font-semibold ${alt?'border-2 border-white text-white':'bg-ambar text-black'}`}>{children}</Link>;
const Page=({t,sub,children})=><><H t={t} sub={sub}/><W cls="py-12">{children}</W></>;
function Layout({children}){const [o,setO]=useState(false);const [th,setTh]=useState(document.documentElement.dataset.theme||'dark');
const flip=()=>{const t=th==='dark'?'light':'dark';document.documentElement.dataset.theme=t;try{localStorage.setItem('mac-theme',t)}catch(e){}setTh(t)};return <>
<a href="#main" className="sr-only focus:not-sr-only p-2">Saltar al contenido</a>
<nav className="bg-surface border-b border-line sticky top-0 z-10"><W cls="flex items-center justify-between h-16">
<Link to="/" className="flex items-center gap-2 font-extrabold text-link text-lg"><Logo c="var(--color-morado)" s={32}/>Alternativa Ciudadana</Link>
<button className="md:hidden" aria-label="Menú" onClick={()=>setO(!o)}>☰</button>
<ul className={`${o?'absolute top-16 left-0 right-0 bg-surface p-5 flex flex-col gap-3':'hidden'} md:static md:flex md:flex-row md:gap-6 md:p-0 text-sm font-semibold`}>
{nav.map(([p,l])=><li key={p}><NavLink to={p} onClick={()=>setO(false)} className={({isActive})=>isActive?'text-rosa':'hover:text-link'}>{l}</NavLink></li>)}
<li><button onClick={flip} aria-label={th==='dark'?'Cambiar a modo claro':'Cambiar a modo oscuro'} className="border border-line rounded-full px-3 py-1">{th==='dark'?'☀ Claro':'☾ Oscuro'}</button></li><li><Link to="/unete" onClick={()=>setO(false)} className="bg-morado text-white rounded-full px-4 py-2">Únete</Link></li></ul></W></nav>
<main id="main">{children}</main>
<footer className="bg-[#0d0614] text-white/85 mt-20 py-12"><W cls="grid md:grid-cols-3 gap-8 text-base"><div><img src="/logo.svg" alt="Alternativa Ciudadana" className="h-14 bg-white rounded p-2"/><p className="mt-3">Movimiento Alternativa Ciudadana (MAC). Santiago de Cali, Valle del Cauca.</p><p className="italic mt-2">Lo que nos une, nos representa.</p></div>
<div><h2 className="font-bold text-white mb-2">Participa</h2><ul><li><Link to="/unete">Afíliate</Link></li><li><Link to="/mi-afiliacion">Portal de la militancia</Link></li><li><Link to="/voluntariado">Voluntariado</Link></li><li><Link to="/donar">Dona</Link></li></ul></div>
<div><h2 className="font-bold text-white mb-2">Legal</h2><ul><li><Link to="/transparencia">Estatutos y cuentas</Link></li><li><Link to="/privacidad">Tratamiento de datos</Link></li></ul></div></W></footer></>}
function Home(){const [n,setN]=useState([]);useEffect(()=>{getJSON('noticias').then(x=>setN(x.slice(0,3))).catch(()=>{})},[]);return <>
<section className="bg-morado text-white overflow-hidden"><W cls="grid md:grid-cols-2 gap-8 items-center py-16 md:py-24"><div>
<h1 className="text-5xl md:text-7xl font-extrabold leading-[1.02] tracking-tight">Gobernar para todos</h1>
<p className="mt-5 text-white/85 max-w-md">Un movimiento de centro a centroizquierda que propone rigor, escucha y acuerdos para construir un país donde la democracia construye.</p>
<div className="mt-8 flex gap-3 flex-wrap"><Btn to="/unete">Afíliate</Btn><Btn to="/programa" alt>Conoce el programa</Btn></div></div>
<div className="flex justify-center"><img src="/logo.svg" alt="Alternativa Ciudadana" className="w-full max-w-md bg-white rounded-2xl p-6"/></div></W></section>
<W cls="py-16"><h2 className="text-3xl font-extrabold mb-6">Lo que nos guía</h2><div className="grid sm:grid-cols-2 gap-x-10 gap-y-6">{valores.map(([t,d])=><div key={t} className="border-l-4 border-ambar pl-4"><h3 className="font-bold text-xl">{t}</h3><p>{d}</p></div>)}</div></W>
<section className="bg-lila py-14"><W><h2 className="text-3xl font-extrabold mb-6">Cuatro ejes de programa</h2><ul className="grid md:grid-cols-2 gap-4">{ejes.map(([t,d])=><li key={t} className="bg-surface p-5 border-t-4 border-rosa"><h3 className="font-bold">{t}</h3><p className="text-base">{d}</p></li>)}</ul><div className="mt-6"><Link className="font-semibold text-link underline" to="/programa">Ver programa completo</Link></div></W></section>
<section className="bg-morado text-white py-14"><W cls="grid md:grid-cols-2 gap-8 items-center"><div><h2 className="text-3xl md:text-4xl font-extrabold">Colombia que funcione para todos</h2><p className="mt-3 text-white/85">Plan de Gobierno Nacional en veinte capítulos: salud, educación, ambiente, seguridad, economía y un Estado digital. Ejecutable dentro del marco institucional vigente, sin reforma constitucional.</p><div className="mt-6"><Btn to="/plan">Lee el plan</Btn></div></div><div className="grid grid-cols-2 gap-4 text-center"><div className="bg-white/10 p-5 rounded-xl"><b className="block text-lg">Iris Maia Escorcia</b><span className="text-sm">Presidencia</span></div><div className="bg-white/10 p-5 rounded-xl"><b className="block text-lg">María Camila Herrera</b><span className="text-sm">Vicepresidencia</span></div></div></W></section>
<W cls="py-16"><h2 className="text-3xl font-extrabold mb-6">Últimas noticias</h2>{n.map(x=><article key={x.id} className="mb-4"><h3 className="font-bold text-xl">{x.title}</h3><p>{x.body}</p></article>)}</W></>}
function Nosotros(){const org=[['Convención Nacional','Máxima autoridad. Se reúne cada dos años; las reformas estatutarias se aprueban por dos tercios. La primera, a más tardar el 20 de diciembre de 2030.'],['Dirección Nacional','Diez miembros con paridad y alternancia de género, elegidos por dos años, más un representante de la Juventud (mayor de 18).'],['Presidencia y Secretaría General','La Presidencia representa política y legalmente al MAC. La Secretaría lleva actas y el registro de afiliados.'],['Tesorería y revisor fiscal','Administra los recursos y reporta ante las autoridades; el revisor fiscal es designado por la Presidencia.'],['Comité de Ética y Garantías','Diez miembros, independientes e imparciales; decide sobre faltas con debido proceso y doble instancia.'],['Veeduría de Transparencia','Verifica la publicación abierta de cuentas y decisiones y recibe observaciones de afiliados y ciudadanos.'],['Consejo Programático y Técnico','Verifica que cada propuesta tenga diagnóstico técnico, fuente verificable y ruta viable.'],['Directorios y Equipos Regionales de Escucha','Organizan a los afiliados en cada departamento, distrito y municipio y recogen las necesidades antes de formular políticas.']];
const hex=[['Ámbar','#f5a31a'],['Morado','#6a2c9e'],['Rosa','#e23d8b']];
const himno=['I\nDe la escucha nace el rumbo,\nde la plaza y del taller,\ndel barrio y de la escuela\nque nos enseñan a ver.\nSin gritos que dividan\nni muros que levantar,\ntendemos puentes de acuerdos\npara poder avanzar.','Coro\n¡Alternativa Ciudadana, un país por construir!\nRigor y cercanía, verdad y pluralidad.\nJuntos, con las manos abiertas,\nColombia, ¡vamos a avanzar!','II\nCon las cuentas claras y abiertas\nsostenemos la razón;\nsi erramos, lo decimos\ny se corrige la acción.\nQue el dato guíe el trabajo,\nque el diálogo abra el portón,\nque ninguna voz se quede\nsin su lugar en la unión.','III\nDesde el joven que despierta\nhasta quien vio tanto ayer,\ncabemos todas y todos\nen un país por hacer.\nCon la tierra bien cuidada,\ncon justicia y seguridad,\nsembramos futuro juntos\nsin odio ni vanidad.'];
return <><H t="Quiénes somos" sub="Una organización de ciudadanos y ciudadanas, libre y voluntaria."/><W cls="py-12 space-y-12"><div className="space-y-5 max-w-3xl">
<p>El Movimiento Alternativa Ciudadana (MAC) es un movimiento político de centro a centroizquierda, socialdemócrata, progresista, reformista y constitucionalista, de ideología escorcianista. Fue constituido como movimiento independiente el 30 de agosto de 2026 en Santiago de Cali por iniciativa de sus fundadoras, Iris Maia Escorcia y María Camila Herrera. Su ámbito es nacional y su duración, indefinida.</p>
<h2 className="text-2xl font-extrabold">Historia</h2><p>Surgió el 23 de abril de 2026 como Movimiento Nueva Síntesis, desde el descontento de Iris Maia Escorcia con los candidatos presentados a las elecciones presidenciales de ese año, la fragmentación de los partidos tradicionales y la creciente polarización del país.</p>
<p>Antes, desde el 29 de diciembre de 2025, Escorcia impulsó un ala reformista dentro del Partido Liberal Colombiano. De allí nació el escorcianismo, que el 30 de agosto de 2026 pasó a ser la ideología fundacional del movimiento.</p>
<h2 className="text-2xl font-extrabold">Rechazo al populismo y al dogmatismo</h2><p>Nos comprometemos a evitar la gestión confrontativa, buscar consensos antes que disputas y reconocer el diálogo interpartidista como pilar de la buena gobernanza.</p></div>
<section><h2 className="text-3xl font-extrabold mb-4">Valores</h2><div className="grid sm:grid-cols-2 gap-x-10 gap-y-5">{valores.map(([t,d])=><div key={t} className="border-l-4 border-ambar pl-4"><h3 className="font-bold text-xl">{t}</h3><p className="text-base">{d}</p></div>)}</div></section>
<section><h2 className="text-3xl font-extrabold mb-4">Cómo nos organizamos</h2><dl className="grid md:grid-cols-2 gap-x-10 gap-y-5">{org.map(([t,d])=><div key={t}><dt className="font-bold text-link">{t}</dt><dd className="text-base">{d}</dd></div>)}</dl>
<p className="mt-5 max-w-3xl">Los candidatos se eligen por consulta interna en la Convención o, de forma excepcional, por el portal de la militancia, con transparencia e igualdad de oportunidades. El MAC puede avalar candidatos invitados y formar coaliciones, sin renunciar a sus valores.</p></section>
<section><h2 className="text-3xl font-extrabold mb-4">Colectivos</h2><p className="max-w-3xl">Espacios de participación y de propuestas: mujeres, jóvenes (con la Juventud Alternativa Ciudadana), pueblos y comunidades étnicas a través de <b>Raíz Ciudadana</b>, población afrodescendiente, personas con discapacidad, población LGBTIQ+ a través de <b>Ciudadanos a Colores</b>, medioambiente, ciencia, tecnología y gobierno abierto.</p></section>
<section><h2 className="text-3xl font-extrabold mb-4">Símbolos</h2><div className="grid md:grid-cols-2 gap-8"><div><img src="/logo.svg" alt="Logo de Alternativa Ciudadana" className="h-20 bg-white rounded p-2"/><p className="mt-3 text-base">Dos trazos que convergen en forma de «A», un arco que los une a modo de puente y un punto superior: la ciudadanía que se encuentra y construye en común.</p><div className="flex gap-3 mt-4">{hex.map(([n,c])=><div key={n} className="text-center text-sm"><div className="w-16 h-16 rounded-lg border border-line" style={{background:c}}/>{n}<br/>{c}</div>)}</div></div>
<div><h3 className="font-bold text-xl mb-2">Lemas</h3><ul className="list-disc pl-6"><li>«Alternativa Ciudadana: gobernar para todos»</li><li>«Lo que nos une, nos representa»</li><li>«Democracia que construye»</li></ul><details className="mt-4"><summary className="cursor-pointer font-bold text-link">Himno de Alternativa Ciudadana</summary><div className="mt-3 grid gap-4">{himno.map((x,i)=><p key={i} className="whitespace-pre-line text-base">{x}</p>)}</div></details></div></div></section></W></>}
function Plan(){return <><H t="Plan de Gobierno Nacional" sub="«Colombia que funcione para todos». Iris Maia Escorcia, Presidencia · María Camila Herrera, Vicepresidencia."/><W cls="py-12 space-y-12">
<section className="max-w-3xl space-y-4"><p>Un conjunto de propuestas concretas, ejecutables dentro de los marcos institucionales existentes: ninguna requiere reforma constitucional. Cada capítulo identifica el nivel de gobierno competente y el instrumento jurídico necesario.</p>
<p>Su ideología es el progresismo responsable: el Estado como garante de derechos y el mercado como herramienta de prosperidad compartida cuando está bien regulado. Cada capítulo conserva su columna vertebral de centroizquierda e incorpora medidas pensadas para generar consenso entre derecha e izquierda: eficiencia estatal, formalización, seguridad ciudadana y disciplina fiscal focalizada. Es un documento vivo, que se actualiza con el diálogo ciudadano.</p>
<a href="/Plan-de-Gobierno-MAC.pdf" className="inline-block rounded-full px-6 py-3 font-semibold bg-ambar text-black">Descargar el plan completo (PDF)</a></section>
<section><h2 className="text-3xl font-extrabold mb-2">Veinte capítulos</h2><p className="mb-4 text-base">Aquí van el diagnóstico y las propuestas más representativas de cada capítulo. El PDF trae todas.</p>
{plan.map(c=><details key={c.n} className="border-b border-line py-3"><summary className="cursor-pointer font-bold text-xl">{c.n}. {c.t}</summary><div className="mt-3 space-y-3 max-w-3xl"><p><b>Diagnóstico.</b> {c.dx}</p><ul className="list-disc pl-6 space-y-1">{c.p.map(x=><li key={x}>{x}</li>)}</ul><p className="text-base"><b>Cómo se ejecuta.</b> {c.e}</p></div></details>)}</section>
<section className="max-w-3xl border-l-4 border-rosa pl-4 space-y-2"><p className="italic">«Ser joven no es un obstáculo para transformar el país, es la razón para hacerlo.» — Iris Maia Escorcia, candidata a la Presidencia</p><p className="italic">«El progreso verdadero no deja a nadie atrás.» — María Camila Herrera, candidata a la Vicepresidencia</p><div className="pt-2"><Btn to="/unete">Súmate al movimiento</Btn></div></section></W></>}
function Programa(){return <><H t="Programa: el escorcianismo" sub="Corriente sociopolítica colombiana ideada por Iris Maia Escorcia, surgida el 28 de agosto de 2026."/><W cls="py-12 space-y-12">
<section className="max-w-3xl space-y-4"><h2 className="text-3xl font-extrabold">¿Qué es?</h2><p>Expresión del progresismo, el reformismo y el socialrepublicanismo. Busca normalizar modelos socialdemócratas y socioliberales, corregir las desigualdades estructurales y avanzar social, política y económicamente, con una separación total del conservadurismo. Se apoya en la avanzada social controlada y en la seguridad nacional.</p></section>
<section><h2 className="text-3xl font-extrabold mb-5">Ejes de gobierno</h2><div className="grid md:grid-cols-2 gap-5">{ejes.map(([t,d])=><div key={t} className="border-l-4 border-ambar pl-4"><h3 className="font-bold text-xl">{t}</h3><p>{d}</p></div>)}</div></section>
<section><h2 className="text-3xl font-extrabold mb-5">Ideas orientadoras</h2><dl className="grid md:grid-cols-2 gap-x-10 gap-y-5">{ideas.map(([t,d])=><div key={t}><dt className="font-bold text-link">{t}</dt><dd>{d}</dd></div>)}</dl></section>
<section className="bg-lila p-6 md:p-10"><h2 className="text-3xl font-extrabold mb-3">Tecnodesarrollismo</h2><p className="max-w-3xl mb-4">Un país posee un potencial científico, tecnológico y de innovación que puede ampliarse con una estrategia liderada por el Estado, sostenida en el largo plazo y protegida de los ciclos de gobierno. Combina el desarrollismo con sectores intensivos en conocimiento. No es de izquierda ni de derecha: es una doctrina de método y prioridades.</p>
<ul className="max-w-3xl list-disc pl-5 mb-6"><li>La tecnología es el motor principal del crecimiento y no se deja solo al azar del mercado.</li><li>El Estado planifica, financia, coordina y, si hace falta, produce, sin monopolio.</li><li>El valor de la investigación debe quedarse en buena parte en el país.</li><li>Todo con límites: privacidad, ambiente, derechos laborales y control de la IA.</li></ul>
<h3 className="font-bold text-xl mb-3">Principios</h3><dl className="grid md:grid-cols-2 gap-5">{tecno.map(([t,d])=><div key={t}><dt className="font-bold">{t}</dt><dd className="text-base">{d}</dd></div>)}</dl></section></W></>}
function Form({kind,fields,send}){const [d,setD]=useState({});const [m,setM]=useState(null);
const on=k=>e=>setD({...d,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value});
const sub=async e=>{e.preventDefault();setM(null);try{await submit(kind,d);setM({ok:1,t:'Recibido. Gracias por participar.'});setD({})}catch(x){setM({t:x.message})}};
const menor=kind==='afiliacion'&&d.nacimiento&&(Date.now()-new Date(d.nacimiento))/31557600000<18;
return <form onSubmit={sub} className="max-w-xl space-y-4">{fields.map(([k,l,t='text'])=>t==='check'?<label key={k} className="flex gap-2 items-start text-base"><input type="checkbox" className="mt-2" checked={!!d[k]} onChange={on(k)}/>{l}</label>:
<label key={k} className="block font-semibold text-base">{l}{t==='area'?<textarea required rows="4" value={d[k]||''} onChange={on(k)} className="block w-full border border-line p-2 bg-surface font-normal"/>:<input required type={t} value={d[k]||''} onChange={on(k)} className="block w-full border border-line p-2 bg-surface font-normal"/>}</label>)}

<input name="web" tabIndex="-1" autoComplete="off" className="hidden" onChange={on('bot-field')}/>
<button className="bg-morado text-white font-semibold rounded-full px-6 py-3">{send}</button>{m&&<p role="status" className={m.ok?'text-link font-bold':'text-rosa font-bold'}>{m.t}</p>}</form>}
const Vol=()=><Page t="Voluntariado" sub="Apoya sin afiliarte: escucha ciudadana y equipos de trabajo, sin voto en los órganos de decisión."><Form kind="voluntariado" send="Quiero ayudar" fields={[['nombre','Nombre completo'],['email','Correo electrónico','email'],['municipio','Municipio'],['area','¿En qué puedes ayudar?','area']]}/></Page>;
const Donar=()=><Page t="Dona" sub="Registra tu intención de aporte. El MAC no acepta recursos ilícitos ni aportes que superen los límites legales y publica sus donantes y cuentas."><Form kind="donacion" send="Registrar aporte" fields={[['nombre','Nombre completo'],['email','Correo electrónico','email'],['monto','Monto en COP','number']]}/><p className="mt-4 text-base">Te contactaremos con las instrucciones de pago. Aún no hay pasarela de pagos conectada.</p></Page>;
const Contacto=()=><Page t="Contacto"><Form kind="contacto" send="Enviar mensaje" fields={[['nombre','Nombre'],['email','Correo electrónico','email'],['mensaje','Mensaje','area']]}/></Page>;
const Juventud=()=><Page t="Juventud Alternativa Ciudadana" sub="Militancia juvenil desde los 14 años."><div className="max-w-3xl space-y-4"><p>La JAC reúne a militantes de 14 a 17 años, con coordinación nacional y territorial elegida por sus miembros. Participan con voz y voto en sus consultas internas y reciben formación política, cívica y técnica adecuada a su edad.</p><p>Es requisito la tarjeta de identidad y la autorización del representante legal, que puede retirarla en cualquier momento. No se usa a menores en propaganda, recolección de fondos ni actividades de riesgo, y hay un canal confidencial de denuncia.</p><p>El MAC promueve candidaturas a los Consejos de Juventud (Leyes 1622 de 2013 y 1885 de 2018). Al cumplir 18 años, pasas a ser afiliado con plenitud de derechos.</p><Btn to="/unete">Afíliate</Btn></div></Page>;
function Noticias(){const [n,setN]=useState([]);useEffect(()=>{getJSON('noticias').then(setN)},[]);return <Page t="Noticias">{n.map(x=><article key={x.id} className="mb-8 max-w-3xl"><time className="text-sm text-link">{x.created.slice(0,10)}</time><h2 className="text-2xl font-bold">{x.title}</h2><p>{x.body}</p></article>)}</Page>}
const Priv=()=><Page t="Tratamiento de datos"><p className="max-w-3xl">Protegemos tus datos conforme a la Ley 1581 de 2012. Solo se usan para la militancia, la participación y la comunicación del movimiento. Los datos de menores no se usan para propaganda electoral personalizada ni se comparten con terceros (art. 18B). Puedes solicitar su eliminación al retirarte. Los formularios se reciben mediante Netlify Forms y solo el equipo autorizado del MAC accede a las respuestas.</p></Page>;
const inp="block w-full border border-line bg-surface p-2 font-normal mt-1";
const post=(u,b,h={})=>fetch(u,{method:'POST',headers:{'Content-Type':'application/json',...h},body:JSON.stringify(b)}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Error');return j});
const Chk=({l,v,on})=><label className="flex gap-2 items-start text-base"><input type="checkbox" className="mt-2" checked={!!v} onChange={on}/><span>{l}</span></label>;
function Unete(){const [d,setD]=useState({tipo:'militante',tipo_doc:'Cédula de ciudadanía'});const [m,setM]=useState('');const [ok,setOk]=useState(null);
const on=k=>e=>setD({...d,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value});
const menor=d.nacimiento&&(Date.now()-new Date(d.nacimiento))/31557600000<18;const mil=d.tipo==='militante';
const sub=async e=>{e.preventDefault();setM('');try{validar(d);setOk(await submit('afiliacion',d))}catch(x){setM(x.message)}};
if(ok)return <Page t="Listo" sub={`Gracias por afiliarte al MAC, ${d.nombre}.`}><div className="max-w-xl space-y-4">{ok.codigo&&<p>Tu código de afiliación es <b className="text-2xl text-link">{ok.codigo}</b>. Guárdalo.</p>}<p>{ok.estado==='pendiente'?'Tu solicitud como militante quedó pendiente de validación. Verificaremos que no haya doble militancia y te incluiremos en el libro de afiliados.':'Ya haces parte como simpatizante: recibirás nuestras actualizaciones.'} Puedes solicitar tu certificado en el <Link className="underline text-link" to="/mi-afiliacion">Portal de la militancia</Link>.</p><Btn to="/">Volver al inicio</Btn></div></Page>;
const card=(v,t,x)=><label className={`block p-4 border-2 cursor-pointer ${d.tipo===v?'border-ambar bg-surface':'border-line'}`}><input type="radio" name="tipo" className="mr-2" checked={d.tipo===v} onChange={()=>setD({...d,tipo:v})}/><b>{t}</b><p className="text-base">{x}</p></label>;
return <Page t="Afíliate al MAC" sub="Pueden afiliarse personas colombianas desde los 14 años. La militancia juvenil se rige por los artículos 18A a 18J de los estatutos.">
<div className="grid md:grid-cols-2 gap-4 max-w-3xl mb-8"><div><h2 className="font-bold text-xl">Simpatizante</h2><p className="text-base">Sigues el movimiento, recibes novedades y participas en encuentros abiertos, sin voto en los órganos (art. 16A). No entras al libro de afiliados.</p></div><div><h2 className="font-bold text-xl">Militante</h2><p className="text-base">Entras al registro formal de afiliados, con voz y voto, derecho a elegir y ser elegido, a postularte con aval y a formación política (art. 16). Puedes cambiar de una a otra cuando quieras.</p></div></div>
<form onSubmit={sub} className="max-w-3xl space-y-5"><fieldset className="grid sm:grid-cols-2 gap-4"><legend className="font-bold text-xl mb-2">Tipo de vinculación</legend>{card('simpatizante','Simpatizante','Quiero mantenerme informado y apoyar sin registro formal.')}{card('militante','Militante','Quiero inscribirme formalmente en el registro de afiliados.')}</fieldset>
<h2 className="font-bold text-xl">Datos personales</h2><div className="grid sm:grid-cols-2 gap-4">
<label className="font-semibold text-base">Tipo de documento<select className={inp} value={d.tipo_doc} onChange={on('tipo_doc')}>{['Cédula de ciudadanía','Tarjeta de identidad','Cédula de extranjería','Pasaporte'].map(x=><option key={x}>{x}</option>)}</select></label>
{[['documento','Número de documento'],['nombre','Nombres'],['apellidos','Apellidos'],['nacimiento','Fecha de nacimiento','date'],['email','Correo electrónico','email'],['celular','Celular','tel']].map(([k,l,t='text'])=><label key={k} className="font-semibold text-base">{l}<input required={!/opcional/.test(l)} type={t} className={inp} value={d[k]||''} onChange={on(k)}/></label>)}
<label className="font-semibold text-base">Departamento<select required className={inp} value={d.departamento||''} onChange={on('departamento')}><option value="">Selecciona</option>{regiones.map(([r,ds])=><optgroup key={r} label={r}>{ds.map(x=><option key={x}>{x}</option>)}</optgroup>)}</select></label>
<label className="font-semibold text-base">Municipio<input required className={inp} value={d.municipio||''} onChange={on('municipio')}/></label></div>
{menor&&<div className="border-2 border-ambar p-4 space-y-3"><p className="text-base">Para militar debes presentar tarjeta de identidad. La autorización de tu representante legal es requisito de validez (art. 18B).</p><Chk l="Mi representante legal autoriza mi afiliación." v={d.tutor_autoriza} on={on('tutor_autoriza')}/></div>}
<h2 className="font-bold text-xl">Declaraciones</h2>
{mil&&<><Chk l="Soy de nacionalidad colombiana, por nacimiento o por adopción." v={d.nacionalidad} on={on('nacionalidad')}/><Chk l="Acepto, cumpliré y socializaré los estatutos, los valores y el Código de Ética del MAC." v={d.acepta_estatutos} on={on('acepta_estatutos')}/><Chk l="Declaro que no pertenezco a otro partido o movimiento político con personería jurídica (prohibición de doble militancia)." v={d.sin_doble_militancia} on={on('sin_doble_militancia')}/></>}
<Chk l={<>Autorizo el tratamiento de mis datos personales según la <Link className="underline text-link" to="/privacidad">política de tratamiento de datos</Link> (Ley 1581 de 2012).</>} v={d.tratamiento_datos} on={on('tratamiento_datos')}/>
<input tabIndex="-1" autoComplete="off" className="hidden" onChange={on('bot-field')}/>
<button className="bg-morado text-white font-semibold rounded-full px-6 py-3">Enviar afiliación</button>{m&&<p role="alert" className="text-rosa font-bold">{m}</p>}
<p className="text-sm opacity-80">Fundamento: estatutos del MAC, arts. 14, 15, 16A y 18A–18J · Ley 1475 de 2011 (registro de afiliados) · Ley 1581 de 2012.</p></form></Page>}
function Q({url,fields,send,show}){const [d,setD]=useState({});const [m,setM]=useState('');const [r,setR]=useState(null);
const sub=async e=>{e.preventDefault();setM('');setR(null);try{setR(await submit(url,d))}catch(x){setM(x.message)}};
return <form onSubmit={sub} className="max-w-xl space-y-4">{fields.map(([k,l,t='text',o])=><label key={k} className="block font-semibold text-base">{l}{t==='area'?<textarea required rows="3" className={inp} value={d[k]||''} onChange={e=>setD({...d,[k]:e.target.value})}/>:t==='sel'?<select required className={inp} value={d[k]||''} onChange={e=>setD({...d,[k]:e.target.value})}><option value="">Selecciona</option>{o.map(x=><option key={x}>{x}</option>)}</select>:<input required={!/opcional/.test(l)} type={t} className={inp} value={d[k]||''} onChange={e=>setD({...d,[k]:e.target.value})}/>}</label>)}
<button className="bg-morado text-white font-semibold rounded-full px-6 py-3">{send}</button>{m&&<p role="alert" className="text-rosa font-bold">{m}</p>}{r&&<div role="status" className="border-2 border-ambar p-4">{show(r)}</div>}</form>}
function MiAfil(){const [t,setT]=useState('c');const id=[['documento','Número de documento'],['email','Correo con el que te afiliaste','email']];
const tabs=[['c','Certificado'],['a','Solicitar aval'],['r','Renunciar']];
return <Page t="Portal de la militancia" sub="Solicita tu certificado, pide aval como candidato o retírate. Tu solicitud llega al equipo del MAC, que responde por correo."><div className="flex gap-2 mb-8 flex-wrap">{tabs.map(([k,l])=><button key={k} onClick={()=>setT(k)} className={`px-4 py-2 rounded-full border ${t===k?'bg-morado text-white border-morado':'border-line'}`}>{l}</button>)}</div>
{t==='c'&&<Q key="c" url="certificado" send="Consultar" fields={id} show={r=>r.netlify?'Solicitud recibida. Te enviaremos el certificado al correo con el que te afiliaste.':<><p><b>{r.nombre}</b></p><p>Código: <b>{r.codigo}</b> · {r.tipo} · estado: <b>{r.estado}</b></p><p className="text-base">Afiliado desde {String(r.created).slice(0,10)}{r.juvenil?' · Juventud Alternativa Ciudadana':''}</p></>}/>}
{t==='a'&&<><p className="max-w-xl mb-4">Solo los militantes activos pueden pedir aval (art. 36). Las candidaturas a cargos de elección popular exigen mayoría de edad; los menores solo pueden aspirar a Consejos de Juventud (art. 18E).</p><Q key="a" url="aval" send="Enviar solicitud" fields={[...id,['cargo','Cargo o corporación','sel',['Concejo','Asamblea','Alcaldía','Gobernación','Cámara','Senado','Junta Administradora Local','Consejo de Juventud']],['territorio','Territorio (municipio o departamento)'],['mensaje','Por qué quieres ser candidato','area']]} show={()=>'Solicitud recibida. El órgano competente la revisará conforme a los estatutos.'}/></>}
{t==='r'&&<><p className="max-w-xl mb-4">Puedes retirarte libremente (art. 16.8). El retiro no genera sanción.</p><Q key="r" url="renuncia" send="Presentar renuncia" fields={[...id,['motivo','Motivo (opcional)','text']].map(x=>x[0]==='motivo'?[x[0],x[1],'text']:x)} show={()=>'Recibimos tu renuncia. La procesaremos y te confirmaremos por correo. Lamentamos verte ir.'}/></>}</Page>}
function Transp(){const [f,setF]=useState(null);useEffect(()=>{getJSON('finanzas').then(setF).catch(()=>setF({campanas:[]}))},[]);
const cop=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
return <><H t="Cuentas claras y datos protegidos, sin letra pequeña" sub="Dos cosas sostienen la confianza en el movimiento: la transparencia financiera y la protección de los datos de quienes se afilian, aportan o escriben."/><W cls="py-12 space-y-14">
<section><h2 className="text-3xl font-extrabold mb-4">Cómo funciona</h2><p className="max-w-3xl mb-4">El MAC publica ingresos, gastos, donantes y contratos (art. 49), actualizados desde el registro contable interno, no con un informe estático.</p><ol className="list-decimal pl-6 max-w-3xl space-y-1"><li>Cada ingreso o gasto se registra por campaña, con concepto, fecha y monto.</li><li>Esta página lee ese registro y recalcula los totales en cada visita.</li><li>Si no hay campaña activa, lo decimos aquí mismo.</li></ol></section>
<section id="finanzas"><h2 className="text-3xl font-extrabold mb-4">Cuentas por campaña</h2>{!f?<p>Cargando información financiera…</p>:!f.campanas.length?<p className="border-l-4 border-ambar pl-4 max-w-3xl">Aún no hay una campaña con movimientos registrados. Cuando exista, sus ingresos y gastos aparecerán en esta sección.</p>:f.campanas.map(c=><div key={c.nombre} className="mb-8"><h3 className="font-bold text-xl">{c.nombre}</h3><p className="text-base mb-2">Ingresos {cop(c.ingresos)} · Gastos {cop(c.gastos)} · Saldo <b>{cop(c.saldo)}</b></p><div className="overflow-x-auto"><table className="w-full text-base"><tbody>{c.movimientos.map(m=><tr key={m.id} className="border-b border-line"><td className="p-2">{m.fecha}</td><td className="p-2">{m.tipo}</td><td className="p-2">{m.concepto}</td><td className="p-2 text-right">{cop(m.monto)}</td></tr>)}</tbody></table></div></div>)}</section>
<section id="proteccion-datos"><h2 className="text-3xl font-extrabold mb-4">Qué hacemos con tus datos</h2><p className="max-w-3xl mb-6">Todo dato que entregas al afiliarte, escribirnos o aportar se trata conforme a la Ley 1581 de 2012.</p><div className="grid md:grid-cols-3 gap-5">{[['Finalidad','Solo para lo que autorizaste: registro de afiliación, comunicaciones o responder tu mensaje.'],['Seguridad','Acceso restringido al equipo que lo necesita. Los datos de menores nunca se usan en propaganda ni se comparten (art. 18B).'],['Derechos ARCO','Conocer, actualizar, rectificar y suprimir tus datos cuando quieras desde el Portal de la militancia o Contacto.']].map(([t,x])=><div key={t} className="bg-surface p-5 border-t-4 border-rosa"><h3 className="font-bold">{t}</h3><p className="text-base">{x}</p></div>)}</div></section>
<section><h2 className="text-3xl font-extrabold mb-4">Documentos</h2><ul className="list-disc pl-6 space-y-2 max-w-3xl"><li><a className="underline text-link" href="/Estatutos-de-MAC.pdf">Estatutos del MAC (PDF)</a></li><li>Actas y decisiones de los órganos: públicas, salvo reserva legal (art. 51).</li><li>Veeduría de Transparencia (art. 29): escríbenos desde <Link className="underline text-link" to="/contacto">Contacto</Link>.</li><li><Link className="underline text-link" to="/privacidad">Política de tratamiento de datos</Link></li></ul></section></W></>}
function AdminFull(){const [k,setK]=useState('');const [s,setS]=useState(null);const [mem,setMem]=useState([]);const [n,setN]=useState({title:'',body:''});const [mv,setMv]=useState({tipo:'ingreso'});const [e,setE]=useState('');
const h={'x-admin-key':k};const g=u=>fetch(u,{headers:h}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);return j});
const load=async()=>{try{setS(await g('/api/admin/submissions'));setMem(await g('/api/admin/members'));setE('')}catch(x){setE(x.message)}};
const act=async f=>{try{await f();await load()}catch(x){setE(x.message)}};
return <Page t="Administración"><div className="space-y-8"><div className="flex gap-2"><input type="password" placeholder="Clave de administración" value={k} onChange={x=>setK(x.target.value)} className="border border-line bg-surface p-2"/><button onClick={load} className="bg-morado text-white px-4 rounded-full">Entrar</button></div>{e&&<p role="alert">{e}</p>}
{s&&<><section><h2 className="font-bold text-xl mb-2">Libro de afiliados ({mem.length})</h2><div className="overflow-x-auto"><table className="text-sm w-full"><tbody>{mem.map(x=><tr key={x.id} className="border-b border-line align-top"><td className="p-2 font-bold">{x.codigo}</td><td className="p-2">{x.nombre} {x.apellidos}<br/>{x.tipo_doc} {x.documento}</td><td className="p-2">{x.tipo}{x.juvenil?' (juvenil)':''}<br/>{x.departamento}, {x.municipio}</td><td className="p-2">{x.estado}</td><td className="p-2 space-x-1">{['activo','suspendido','retirado'].map(st=><button key={st} onClick={()=>act(()=>post('/api/admin/members/'+x.id,{estado:st},h))} className="border border-line px-2 rounded">{st}</button>)}</td></tr>)}</tbody></table></div></section>
<section className="max-w-xl space-y-2"><h2 className="font-bold text-xl">Publicar noticia</h2><input placeholder="Título" value={n.title} onChange={x=>setN({...n,title:x.target.value})} className={inp}/><textarea placeholder="Texto" value={n.body} onChange={x=>setN({...n,body:x.target.value})} className={inp}/><button onClick={()=>act(async()=>{await post('/api/admin/news',n,h);setN({title:'',body:''})})} className="bg-ambar text-black px-4 py-2 rounded-full font-semibold">Publicar</button></section>
<section className="max-w-xl space-y-2"><h2 className="font-bold text-xl">Registrar movimiento financiero</h2>{[['campana','Campaña'],['concepto','Concepto o fuente'],['fecha','Fecha','date'],['monto','Monto COP','number']].map(([a,l,t='text'])=><input key={a} type={t} placeholder={l} value={mv[a]||''} onChange={x=>setMv({...mv,[a]:x.target.value})} className={inp}/>)}<select value={mv.tipo} onChange={x=>setMv({...mv,tipo:x.target.value})} className={inp}><option>ingreso</option><option>gasto</option></select><button onClick={()=>act(()=>post('/api/admin/movimientos',mv,h))} className="bg-ambar text-black px-4 py-2 rounded-full font-semibold">Registrar</button></section>
<section><h2 className="font-bold text-xl mb-2">Otros registros ({s.length})</h2><div className="overflow-x-auto"><table className="text-sm w-full"><tbody>{s.map(x=><tr key={x.id} className="border-b border-line align-top"><td className="p-2 font-bold">{x.kind}</td><td className="p-2">{x.created}</td><td className="p-2">{Object.entries(x.data).map(([a,b])=>`${a}: ${b}`).join(' | ')}</td></tr>)}</tbody></table></div></section></>}</div></Page>}
const Admin=()=>NETLIFY?<Page t="Administración"><p className="max-w-2xl">En esta versión (Netlify) las solicitudes llegan al panel de Netlify, en Forms: ahí las ves, las exportas a CSV y configuras avisos por correo. Las noticias y las cuentas se editan en los archivos noticias.json y finanzas.json.</p></Page>:<AdminFull/>;
export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/nosotros" element={<Nosotros/>}/><Route path="/programa" element={<Programa/>}/><Route path="/plan" element={<Plan/>}/><Route path="/juventud" element={<Juventud/>}/><Route path="/noticias" element={<Noticias/>}/><Route path="/transparencia" element={<Transp/>}/><Route path="/unete" element={<Unete/>}/><Route path="/mi-afiliacion" element={<MiAfil/>}/><Route path="/voluntariado" element={<Vol/>}/><Route path="/donar" element={<Donar/>}/><Route path="/contacto" element={<Contacto/>}/><Route path="/privacidad" element={<Priv/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<Page t="Página no encontrada"><Btn to="/">Volver al inicio</Btn></Page>}/></Routes></Layout>}
